[package]
name = "cargo-script"
version = "0.2.0"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

description = "A Cargo subcommand designed to let people quickly and easily run Rust \"scripts\" which can make use of Cargo's package ecosystem."
repository = "https://github.com/DanielKeep/cargo-script"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["cargo", "script"]

build = "build.rs"

exclude = [
    "scripts/*",
    ".travis.yml",
]

[dependencies]
clap = "2.23.2"
env_logger = "0.4.2"
hoedown = "6.0.0"
lazy_static = "0.2.6"
log = "0.3.7"
regex = "0.2.1"
rustc-serialize = "0.3.23"
shaman = "0.1.0"
time = "0.1.36"
toml = "0.2.1" # toml 0.3 incompatible with Rust < 1.14.

[target.i686-pc-windows-gnu.dependencies]
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[target.i686-pc-windows-msvc.dependencies]
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[target.x86_64-pc-windows-gnu.dependencies]
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[target.x86_64-pc-windows-msvc.dependencies]
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[dev-dependencies]
gcc = "0.3.45"
scan-rules = "0.2.0"
tempdir = "0.3.5"

[build-dependencies]
rustc_version = "0.1.7" # version 0.2 incompatible with Rust < 1.14

[profile.release]
lto = true
