[package]
name = "rust-script"
version = "0.2.0"
# edition = "2018"
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]

description = "Command-line tool to run Rust \"scripts\" which can make use of crates."
repository = "https://github.com/fornwall/rust-script"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["cargo", "script"]
categories = ["command-line-utilities", "development-tools"]

exclude = [
    "scripts/*",
    ".travis.yml",
]

[features]
default = ["suppress-cargo-output"]
suppress-cargo-output = ["crossbeam-channel"]

[dependencies]
crossbeam-channel = { version = "0.5", optional = true }
clap = "2"
env_logger = "0.8"
pulldown-cmark = "0.8"
itertools = "0.9"
lazy_static = "1"
log = "0.4"
open = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shaman = "0.1"
time = "0.2"
toml = "0.5"

[target.'cfg(windows)'.dependencies]
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"
winreg = "0.4.0"

[target.'cfg(unix)'.dependencies]
atty = "0.2.2"

[dev-dependencies]
scan-rules = "0.2.0"
tempfile = "3"

[profile.release]
lto = true
