[package]
name = "rust-script"
version = "0.2.0"
# edition = "2018"
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]

description = "Command-line tool to run Rust \"scripts\" which can make use of crates."
repository = "https://github.com/fornwall/rust-script"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["cargo", "script"]
categories = ["command-line-utilities", "development-tools"]

build = "build.rs"

exclude = [
    "scripts/*",
    ".travis.yml",
]

[features]
default = ["suppress-cargo-output"]
suppress-cargo-output = ["chan"]

[dependencies]
chan = { version = "0.1.19", optional = true }
clap = "2.33.3"
env_logger = "0.8.1"
hoedown = "6.0.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.11"
open = "1.4.0"
regex = "1.4.1"
rustc-serialize = "0.3.24"
semver = "0.11.0"
shaman = "0.1.0"
time = "0.2.22"
toml = "0.2.1"

[target.'cfg(windows)'.dependencies]
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"
winreg = "0.4.0"

[target.'cfg(unix)'.dependencies]
atty = "0.2.2"

[dev-dependencies]
gcc = "0.3.45"
scan-rules = "0.2.0"
tempdir = "0.3.5"

[build-dependencies]
rustc_version = "0.1.7"

[profile.release]
lto = true
