[package]
name = "cargo-script"
version = "0.1.3"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

[dependencies]
env_logger = "0.3.1"
hoedown = { path="hoedown" }
log = "0.3.1"
regex = "0.1.33"
rustc-serialize = "0.3.14"
shaman = "0.1.0"
time = "0.1.25"
toml = "0.1.20"

[dependencies.clap]
version = "0.10.2"

# Disable the "color" feature because it just outputs garbage on Windows.
default-features = false
features = ["suggestions"]

[target.i686-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
winapi = "0.2.2"
uuid-sys = "0.1.2"

[target.x86_64-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
winapi = "0.2.2"
uuid-sys = "0.1.2"

[profile.release]
lto = true
