name: CI

on: push

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1
    - name: Run unit tests
      run: cargo test
    - name: Run script tests
      if: runner.os != 'Windows'
      run: ./tests/scripts/test-runner.sh

  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting with rustfmt
      run: cargo fmt -- --check
